### ISSUE TITLE
iOS - App crashes when load full image size

### ISSUE THREAD

**Issue by LSmint** [NativeScript/nativescript-imagepicker#209] opened 2018-08-24 18:00 UTC
I was encountered an issue after loaded the image while using ImageSource module. The trace log shows 'Unable to load image data, <private>' when selected a large image size such as 3000 width x 2000 height.

Here is how i called the imagepicker and convert it to imagesource:
```JS
let context = imagepicker.create({
                mode:"single",
                mediaType:1
            });
            context.authorize().then(() => {
                return context.present();
            })
            .then((selection)=>{
                selection.forEach(function(selected){
                    let source = new ImageSourceModule.ImageSource();
                    source.fromAsset(selected).then((source) => {
                           console.log(source.width+"x"+source.height); <-- 3000 x 3000
                    })
                })
            },(error) => {
                console.log("Error: " + error);
                that.router.back();
            });
```
After tried a few times to reselect the image, i get another error and app was crashed due to memory leaked. "Connection to assetsd was interrupted or assetsd die. Unbalanced calls to begin/end appearance transitions for <UIViewControllerImpl: 0x12bd13230>. Received memory warning." 

Any proper way to get the image source or resize the image before load the image source? I'm using the latest version of nativescript-imagepicker.

**Comment by NickIliev** [comment] 2018-08-31 13:18
@LSmint 300 x 2000 is not an extremely large image and should not lead to OOM. However, please do let me know what is the device you are using in this scenario - I've tested on several iPhones but was not able to reproduce anything close to a memory exception. Apart from that, you can't modify the ImageAssset size but only the size of the created ImageSource.

**Comment by NickIliev** [comment] 2018-09-18 10:13
Closing this one as the issue seems related to the image cropper and not to nativescript-imagepicker.

**Closed by NickIliev** 2018-09-18 10:13 UTC
Labels: os: ios, question

**Comment by NatanijelVasic** [comment] 2018-10-30 17:05
Actually I get a similar memory problem when using the image-picker plugin by itself. In fact, even on the demo app, the memory usage is way higher than expected.

I posted out it here:
https://github.com/NativeScript/nativescript-imagepicker/issues/222
