### ISSUE TITLE
Conflicts with nativescript-telerik-ui-pro

### ISSUE THREAD

**Issue by kwong93** [NativeScript/nativescript-imagepicker#50] opened 2016-11-30 18:54 UTC
I have `nativescript-imagepicker` installed, version 2.4.1, and `nativescript-telerik-ui-pro` version 1.4.1. When I run it on android, gradle fails with this error:

```
:processF0F1F2F3F4F5F6DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5F6DebugResources'.
> Error: more than one library with package name 'com.telerik.android.common'
```

It was working with 2.3.1 version of imagepicker.

I have nativescript 2.4 installed

Somebody else had similar problem I think: https://github.com/NativeScript/nativescript-cli/issues/2258

**Comment by markfarl** [comment] 2017-02-02 13:20
I managed to get around this issue by deleting the 
>nativescriptproject\node_modules\nativescript-imagepicker\node_modules\nativescript-telerik-ui

folder and deleting reference to it in the 
> nativescriptproject\node_modules\nativescript-imagepicker\package.json

Inside **dependencies: { }** line 16/17

**Comment by tsonevn** [comment] 2017-02-16 12:48
I am attaching summarized steps with a workaround, which resolved this behavior.

1. open `node_modules` and delete `nativescript-telerik-ui` folder.
2. open `node_modules/nativescript-imagepicker/package.json` file.
search for `nativescript-telerik-ui` and change the dependency name to `nativescript-telerik-ui-pro`
3.open `node_modules/nativescript-imagepicker/images.ios.js` file and replace 
`var listview_1 = require("nativescript-telerik-ui/listview");`
with 
`var listview_1 = require("nativescript-telerik-ui-pro/listview");`
4. the last step is to remove platform with `tns platform remove <platform_name>`
5. build with `tns run <platform_name>`

Keep in mind that if you remove node_modulesfolder you should make those changes again.

**Comment by NgSculptor** [comment] 2017-03-17 18:29
Any update on this bug? Still need to use workaround?

**Comment by RyanSMurphy** [comment] 2017-04-26 17:59
can you create a permanent workaround for this please rather than having to follow those steps on each npm install

**Comment by tsonevn** [comment] 2017-04-27 08:59
Hi @RyanSMurphy,
Thank you for writing us
This issue is still opened and the problem with  `nativescript-telerik-ui-pro` and `nativescript-imagepicker` in the same app should be resolved in the upcoming release 3.0.

**Comment by RyanSMurphy** [comment] 2017-05-03 11:36
@tsonevn When will this be released? The app is working great on ios simulator, but the app crashes when on real device and im having trouble working it out because i cant get logs from actual ios device. any suggestions?

**Comment by tsonevn** [comment] 2017-05-03 13:19
Hi @RyanSMurphy,
The new version of NativeScript 3.0 is officially published in npm and you could upgrade the platform on your side.
Regarding the release of UI for NativeScript. The new version of `nativescript-telerik-ui-pro` 2.0 will be available tomorrow.

**Comment by RyanSMurphy** [comment] 2017-05-03 13:32
Where do you find out the details of the pending v2.0 for telerik pro?

**Comment by tsonevn** [comment] 2017-05-04 14:45
Hi @RyanSMurphy 
UI for NativeScript 2.0 was released today and you could find it in NPM [here](https://www.npmjs.com/package/nativescript-telerik-ui-pro).
Let me know if you have some further issues while using the new version.

**Comment by nicolam1** [comment] 2017-05-10 16:57
Any updates on this? We cannot use this plugin when using ui-pro

**Comment by tsonevn** [comment] 2017-05-12 14:18
Hi @nicolam1,
After migration `nativescript-imagepicker` plugin to 3.0 it is possible to use it in the same app with `nativescript-telerik-ui-pro` 2.0.1. For your convenience, I am attaching sample app, which you could test on your side. 
Bear in mind that I tested this scenario with NativeScript 3.0.

[Archive.zip](https://github.com/NativeScript/nativescript-imagepicker/files/996955/Archive.zip)

**Comment by nicolam1** [comment] 2017-05-12 14:32
Thank you!

**Comment by antkiewicz** [comment] 2017-06-12 20:09
@tsonevn Doesn't `nativescript-telerik-ui-pro` contain the same components as `nativescript-telerik-ui` package, plus few extra ones? Would it be possible to use UI Pro package when it is present instead of requiring to install UI just to use this image picker? That way unnecessary duplication of components could be avoided.

**Comment by tsonevn** [comment] 2017-06-13 11:23
Hi @antkiewicz,
Indeed `nativescript-telerik-ui-pro` contains all component from the free version, however, using the both plugins in the same app should work as expected. 
In case you still want to have only  `nativescript-telerik-ui-pro` plugin as a dependency you could review [this comment](https://github.com/NativeScript/nativescript-imagepicker/issues/50#issuecomment-280321679), where it is shown how to replace free version with the pro one in the image picker plugin

**Comment by RyanSMurphy** [comment] 2017-07-10 15:35
This still doesn't work. You must find a way to either make them both work or add this information to your documenattion.

**Comment by tsonevn** [comment] 2017-07-11 06:53
Hi @RyanSMurphy,
Could you specify the error, which is thrown when you are using the both plugins in the same app? Also verify, that you are using the latest version of NativeScript and `nativescript-imagepicker`.

**Comment by RyanSMurphy** [comment] 2017-07-12 10:17
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1F2F3F4F5F6F7F8DebugResources'.
> Error: more than one library with package name 'com.telerik.android.common'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.147 secs
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.

Using latest nativescript version with "nativescript-imagepicker": "^3.0.2",

**Comment by tsonevn** [comment] 2017-07-12 10:38
HI @RyanSMurphy ,
Which version of NativeScript do you use? You could verify this by running `tns --version`. Make sure that you are using `3.1.2`.

**Comment by RyanSMurphy** [comment] 2017-07-12 11:20
I am indeed using 3.1.2. 

It works on iOS, but not on Android.

**Comment by tsonevn** [comment] 2017-07-12 12:32
@RyanSMurphy,
In case this issue is reproducible only on Android, verify whether you have installed Build-tools 25.0.2 in your `Android SDK Manager`.
![screen shot 2017-07-12 at 3 30 32 pm](https://user-images.githubusercontent.com/17448734/28117723-4062131a-6717-11e7-908f-bb4820e8ca77.png)

**Comment by RyanSMurphy** [comment] 2017-07-13 09:09
![screen shot 2017-07-13 at 10 09 07](https://user-images.githubusercontent.com/1730103/28158977-60602c3c-67b3-11e7-9746-c1643be08097.png)

@tsonevn As you can see, I have up to 26 installed

**Comment by tsonevn** [comment] 2017-07-13 09:38
Hi @RyanSMurphy,
Could you select the `Show Package Details` checkbox and fo verify again specifically for Build-tools 25.0.2?
![screenshot 40](https://user-images.githubusercontent.com/17448734/28160206-278b5674-67c8-11e7-8fa0-6069a5fd12ad.png)

**Comment by RyanSMurphy** [comment] 2017-07-13 09:50
So it didnt have that installed. I installed it, went straight back to my terminal, deleted android folder, re ran build, and it still failed.

**Comment by RyanSMurphy** [comment] 2017-07-13 09:52
![screen shot 2017-07-13 at 10 51 40](https://user-images.githubusercontent.com/1730103/28160825-49d47eea-67b9-11e7-8214-d58a53c8f640.png)

@tsonevn

**Comment by RyanSMurphy** [comment] 2017-07-13 09:53
FYI these are my dependencies in package.json for them both at root:


		```
"nativescript-telerik-ui": "^3.0.1",
		"nativescript-telerik-ui-pro": "file:nativescript-ui-pro.tgz",
```

**Comment by VladimirAmiorkov** [comment] 2017-07-14 07:11
Hi @RyanSMurphy ,

There is not need to add both the "non pro" and the "pro" version of the plugin. The pro version contains all of the components plus some additional components. Since the `nativescript-telerik-ui` and `nativescript-telerik-ui-pro` are using the same native iOS and ANdroid libraries, on Android when you add the same library that contains the same files/classes the gradle build will fail.

Can you try to remove the  `nativescript-telerik-ui` from the dependencies section of your package.json leaving only the `nativescript-telerik-ui-pro` and let us know if the issue has been resolved?

**Comment by RyanSMurphy** [comment] 2017-07-14 09:27
When i remove nativescript-telerik-ui it also breaks on ios. Any updates on this?

**Comment by RyanSMurphy** [comment] 2017-07-27 15:15
@tsonevn any updates on this?

**Comment by EddyVerbruggen** [comment] 2017-08-12 11:44
Just proposed PR #104 to fix this nasty issue.

**Closed** 2017-08-16 07:39 UTC
Labels: bug, planned, S: high
